[project]
name = "mcp-directory-server-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.20.0",
    "toolbox-core>=0.5.3",
]
